import {APIKEY, APPID, AUTHDOMAIN, DATABASEURL, MESSAGINGSENDERID, PROJECTID, STORAGEBUCKET} from '@env';

export default {
    APIKEY, APPID, AUTHDOMAIN, DATABASEURL, MESSAGINGSENDERID, PROJECTID, STORAGEBUCKET
}