name: react-native-android-build-apk
on:
  push:
    branches:
      - master
      - dev
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Create env file
        working-directory: ./
        run: |
          touch .env
          echo APIKEY=${{ secrets.APIKEY }} >> .env
          echo AUTHDOMAIN=${{ secrets.AUTHDOMAIN }} >> .env
          echo DATABASEURL=${{ secrets.DATABASEURL }} >> .env
          echo PROJECTID=${{ secrets.PROJECTID }} >> .env
          echo STORAGEBUCKET=${{ secrets.STORAGEBUCKET }} >> .env
          echo MESSAGINGSENDERID=${{ secrets.MESSAGINGSENDERID }} >> .env
          echo APPID=${{ secrets.APPID }} >> .env
      - name: Create keystore for sign
        working-directory: ./android/app
        run: echo ${{secrets.KEYSTORE_FILE}} | base64 -d > debug.keystore
      - name: Build Android Release
        working-directory: ./android
        run: |
          chmod +x ./gradlew
          export ORG_GRADLE_PROJECT_RELEASE_STORE_FILE=/app/debug.keystore
          export ORG_GRADLE_PROJECT_RELEASE_STORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}
          export ORG_GRADLE_PROJECT_RELEASE_KEY_ALIAS=${{ secrets.KEY_ALIAS }}
          export ORG_GRADLE_PROJECT_RELEASE_KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}
          ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
